services:
  - type: web
    name: portfolio-django
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,yourdomain.com"
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: portfolio-db
    plan: free
    databaseName: portfolio
    user: portfolio_user