# Generated by Django 5.0.6 on 2025-09-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Web Developer & Designer, Creating beautiful, functional websites that deliver results!'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Besong Wisdom ', max_length=100),
        ),
    ]
