# Generated by Django 5.0.2 on 2025-09-09 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('profile_picture', models.ImageField(upload_to='profiles/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('linkedin', models.TextField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('github', models.TextField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('twitter', models.TextField(blank=True, validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
