# Generated by Django 5.0.2 on 2025-09-09 19:39

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_testimonial_profile_resume_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
