# Generated by Django 5.0.2 on 2025-09-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, default='Creating beautiful, functional websites that deliver results.'),
        ),
    ]
