# Generated by Django 5.0.2 on 2025-09-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_profile_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='abpout_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
