# Generated by Django 5.0.2 on 2025-09-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_abpout_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='abpout_picture',
            new_name='about_picture',
        ),
    ]
