# Generated by Django 5.0.2 on 2025-09-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_abpout_picture_profile_about_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_picture',
            field=models.ImageField(default='profiles/default_about.jpg', upload_to='profiles/'),
        ),
    ]
